[tools]
cargo = "latest"
delta = "latest"
java = "17"
node = "18.17.1"
python = "3.12"
ruby = "3.4.4"
rust = "1.89.0"

[settings]

[settings.node]
flavor = "glibc-227"
compile = true
gpg_verify = false
